/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_floodlight_brightness: 0
      i_ip: ''
      i_laser_dot_brightness: 0
      i_mx_id: ''
      i_nn_type: spatial
      i_pipeline_type: RGBD
      i_usb_speed: SUPER_PLUS
    left:
      i_board_socket_id: 1
      i_fps: 60.0
      i_height: 720
      i_max_q_size: 30
      i_publish_topic: false
      i_resolution: '720'
      i_width: 1280
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    nn:
      i_label_map:
      - background
      - aeroplane
      - bicycle
      - bird
      - boat
      - bottle
      - bus
      - car
      - cat
      - chair
      - cow
      - diningtable
      - dog
      - horse
      - motorbike
      - person
      - pottedplant
      - sheep
      - sofa
      - train
      - tvmonitor
      i_max_q_size: 30
      i_nn_config_path: depthai_ros_driver/mobilenet
      i_num_inference_threads: 2
      i_num_pool_frames: 4
    rgb:
      i_board_socket_id: 0
      i_enable_preview: false
      i_fps: 30.0
      i_height: 720
      i_interleaved: false
      i_keep_preview_aspect_ratio: true
      i_max_q_size: 30
      i_preview_size: 416
      i_publish_topic: true
      i_resolution: '1080'
      i_set_isp_scale: true
      i_width: 1280
      r_exposure: 20000
      r_focus: 1
      r_iso: 800
      r_set_man_exposure: false
      r_set_man_focus: false
      r_set_man_whitebalance: false
      r_whitebalance: 3300
    right:
      i_board_socket_id: 2
      i_fps: 60.0
      i_height: 720
      i_max_q_size: 30
      i_publish_topic: false
      i_resolution: '720'
      i_width: 1280
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    stereo:
      i_align_depth: true
      i_bilateral_sigma: 500
      i_board_socket_id: 0
      i_decimation_filter_decimation_factor: 1
      i_decimation_filter_decimation_mode: PIXEL_SKIPPING
      i_depth_filter_size: 7
      i_depth_preset: HIGH_ACCURACY
      i_enable_deciamation_filter: false
      i_enable_distortion_correction: false
      i_enable_spatial_filter: false
      i_enable_temporal_filter: false
      i_enable_threshold_filter: false
      i_extended_disp: false
      i_height: 720
      i_lr_check: true
      i_lrc_threshold: 5
      i_max_q_size: 30
      i_rectify_edge_fill_color: 0
      i_spatial_filter_alpha: 0.5
      i_spatial_filter_delta: 20
      i_spatial_filter_hole_filling_radius: 2
      i_spatial_filter_iterations: 1
      i_stereo_conf_threshold: 255
      i_temporal_filter_alpha: 0.4000000059604645
      i_temporal_filter_delta: 20
      i_temporal_filter_persistency: VALID_2_IN_LAST_4
      i_threshold_filter_max_range: 15000
      i_threshold_filter_min_range: 400
      i_width: 1280
    use_sim_time: false
