/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_floodlight_brightness: 0
      i_ip: ''
      i_laser_dot_brightness: 800
      i_mx_id: ''
      i_nn_type: spatial
      i_pipeline_type: RGBD
      i_usb_port_id: ''
      i_usb_speed: SUPER_PLUS
    left:
      i_board_socket_id: 1
      i_calibration_file: ''
      i_fps: 30.0
      i_height: 720
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_publish_topic: false
      i_resolution: '720'
      i_width: 1280
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet
      i_disable_resize: false
    oak:
      rgb:
        image_raw:
          format: jpeg
          jpeg_quality: 95
          png_level: 3
          tiff:
            res_unit: inch
            xdpi: -1
            ydpi: -1
      stereo:
        image_raw:
          format: jpeg
          jpeg_quality: 95
          png_level: 3
          tiff:
            res_unit: inch
            xdpi: -1
            ydpi: -1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    rgb:
      i_board_socket_id: 0
      i_calibration_file: ''
      i_enable_preview: false
      i_fps: 30.0
      i_height: 720
      i_interleaved: false
      i_keep_preview_aspect_ratio: true
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_preview_size: 300
      i_publish_topic: true
      i_resolution: '1080'
      i_set_isp_scale: true
      i_width: 1280
      r_exposure: 20000
      r_focus: 1
      r_iso: 800
      r_set_man_exposure: false
      r_set_man_focus: false
      r_set_man_whitebalance: false
      r_whitebalance: 3300
    right:
      i_board_socket_id: 2
      i_calibration_file: ''
      i_fps: 30.0
      i_height: 720
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_publish_topic: false
      i_resolution: '720'
      i_width: 1280
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    stereo:
      i_align_depth: true
      i_output_disparity: false
      i_bilateral_sigma: 0
      i_board_socket_id: 0
      i_depth_filter_size: 5
      i_depth_preset: HIGH_ACCURACY
      i_enable_decimation_filter: false
      i_enable_distortion_correction: false
      i_enable_spatial_filter: false
      i_enable_speckle_filter: false
      i_enable_temporal_filter: false
      i_enable_threshold_filter: false
      i_extended_disp: false
      i_height: 720
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_lr_check: true
      i_lrc_threshold: 10
      i_max_q_size: 30
      i_rectify_edge_fill_color: 0
      i_stereo_conf_threshold: 255
      i_width: 1280
    use_sim_time: false