/oak:
  camera_i_enable_imu: true
  camera_i_enable_ir: true
  camera_i_floodlight_brightness: 0.0
  camera_i_ip: ''
  camera_i_laser_dot_brightness: 800.0
  camera_i_mx_id: ''
  camera_i_nn_type: spatial
  camera_i_pipeline_type: RGBD
  camera_i_usb_port_id: ''
  camera_i_usb_speed: SUPER_PLUS
  imu_i_max_q_size: 30
  left_i_board_socket_id: 1
  left_i_calibration_file: ''
  left_i_fps: 30.0
  left_i_height: 720
  left_i_low_bandwidth: false
  left_i_low_bandwidth_quality: 50
  left_i_max_q_size: 30
  left_i_preview_size: 416
  left_i_publish_topic: false
  left_i_resolution: '720'
  left_i_set_isp_scale: true
  left_i_width: 1280
  left_r_exposure: 1000
  left_r_focus: 1
  left_r_iso: 800
  left_r_keep_preview_aspect_ratio: true
  left_r_set_man_exposure: false
  left_r_set_man_focus: false
  left_r_set_man_whitebalance: false
  left_r_whitebalance: 3300
  nn_i_nn_config_path: depthai_ros_driver/mobilenet
  rgb:
    image_raw:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  rgb_i_board_socket_id: 0
  rgb_i_calibration_file: ''
  rgb_i_enable_preview: false
  rgb_i_fps: 60.0
  rgb_i_height: 720
  rgb_i_interleaved: true
  rgb_i_keep_preview_aspect_ratio: true
  rgb_i_low_bandwidth: false
  rgb_i_low_bandwidth_quality: 50
  rgb_i_max_q_size: 30
  rgb_i_preview_size: 416
  rgb_i_publish_topic: true
  rgb_i_resolution: '1080'
  rgb_i_set_isp_scale: true
  rgb_i_width: 1280
  rgb_r_exposure: 1000
  rgb_r_focus: 1
  rgb_r_iso: 800
  rgb_r_keep_preview_aspect_ratio: true
  rgb_r_set_man_exposure: false
  rgb_r_set_man_focus: false
  rgb_r_set_man_whitebalance: false
  rgb_r_whitebalance: 3300
  right_i_board_socket_id: 2
  right_i_calibration_file: ''
  right_i_fps: 30.0
  right_i_height: 720
  right_i_low_bandwidth: false
  right_i_low_bandwidth_quality: 50
  right_i_max_q_size: 30
  right_i_preview_size: 416
  right_i_publish_topic: false
  right_i_resolution: '720'
  right_i_set_isp_scale: true
  right_i_width: 1280
  right_r_exposure: 1000
  right_r_focus: 1
  right_r_iso: 800
  right_r_keep_preview_aspect_ratio: true
  right_r_set_man_exposure: false
  right_r_set_man_focus: false
  right_r_set_man_whitebalance: false
  right_r_whitebalance: 3300
  stereo:
    image_raw:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  stereo_i_align_depth: true
  stereo_i_bilateral_sigma: 0
  stereo_i_board_socket_id: 0
  stereo_i_calibration_file: ''
  stereo_i_decimation_filter_decimation_factor: 1
  stereo_i_decimation_filter_decimation_mode: PIXEL_SKIPPING
  stereo_i_depth_filter_size: 5
  stereo_i_depth_preset: HIGH_ACCURACY
  stereo_i_enable_decimation_filter: false
  stereo_i_enable_distoartion_correction: false
  stereo_i_enable_spatial_filter: false
  stereo_i_enable_temporal_filter: false
  stereo_i_enable_threshold_filter: false
  stereo_i_extended_disp: false
  stereo_i_height: 720
  stereo_i_low_bandwidth: false
  stereo_i_low_bandwidth_quality: 50
  stereo_i_lr_check: true
  stereo_i_lrc_threshold: 10
  stereo_i_max_q_size: 30
  stereo_i_rectify_edge_fill_color: 0
  stereo_i_spatial_filter_alpha: 0.5
  stereo_i_spatial_filter_delta: 20
  stereo_i_spatial_filter_hole_filling_radius: 2
  stereo_i_spatial_filter_iterations: 1
  stereo_i_stereo_conf_threshold: 255
  stereo_i_temporal_filter_alpha: 0.4
  stereo_i_temporal_filter_delta: 20
  stereo_i_temporal_filter_persistency: VALID_2_IN_LAST_4
  stereo_i_threshold_filter_max_range: 15000
  stereo_i_threshold_filter_min_range: 400
  stereo_i_width: 1280